### ISSUE TITLE
点赞google会报密码丢失的错

### ISSUE THREAD

**Issue by hanzhongzi** [zhenqicai/hugo-theme-kiwi#1]
点赞google会报密码丢失的错

**Comment by zhenqicai** [comment]
【中文】：你好，可否截图报错的原因吗？单是这样文字描述是找不到问题出在哪里的！
【English】： Hello, can you take a screenshot of the error report? It’s impossible to find out where the problem lies just by describing it in words like this!

**Comment by zhenqicai** [comment]
@hanzhongzi 【中文】：你好，可否截图报错的原因吗？单是这样文字描述是找不到问题出在哪里的！
【English】： Hello, can you take a screenshot of the error report? It’s impossible to find out where the problem lies just by describing it in words like this!
