### ISSUE TITLE
报错了，老哥方便帮忙看一下吗

### ISSUE THREAD

**Issue by ccfread** [zhenqicai/hugo-theme-kiwi#2]
G:\hugo\GO\cc>hugo server
Watching for changes in G:\hugo\GO\cc\{archetypes,assets,content,data,i18n,layouts,static,themes}
Watching for config changes in G:\hugo\GO\cc\config.yaml
Start building sites …
hugo v0.123.8-5fed9c591b694f314e5939548e11cc3dcb79a79c+extended windows/amd64 BuildDate=2024-03-07T13:14:42Z VendorInfo=gohugoio

ERROR "G:\hugo\GO\cc\themes\hugo-theme-kiwi\layouts\_default\list.html:9:1": parse failed: template: _default/list.html:9: undefined variable "$paginator"
Built in 77 ms
Error: error building site: "G:\hugo\GO\cc\themes\hugo-theme-kiwi\layouts\_default\list.html:9:1": parse failed: template: _default/list.html:9: undefined variable "$paginator"

**Comment by zhenqicai** [comment]
@ccfread  不好意思，现在才回复你，你可以 pull 最新代码就可以了！
